spring:
  datasource:
    url: jdbc:h2:mem:conferences-db
  h2:
    console:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ebank-realm
          jwk-set-uri: http://localhost:8080/realms/ebank-realm/protocol/openid-connect/certs